version: "3.5"
services:

  m3db_seed:
    networks:
      - backend
    image: quay.io/m3/m3dbnode:latest
    volumes:
      - "./m3dbnode.yml:/etc/m3dbnode/m3dbnode.yml"
    environment:
      - M3DB_HOST_ID=m3db_seed

  m3coordinator01:
    expose:
      - "7201"
      - "7204"
    ports:
      - "0.0.0.0:7201:7201"
      - "0.0.0.0:7204:7204"
    networks:
      - backend
    image: quay.io/m3/m3coordinator:latest
    volumes:
      - "./m3coordinator.yml:/etc/m3coordinator/m3coordinator.yml"

  prometheus01:
    networks:
      - backend
    image: prom/prometheus:latest
    volumes:
      - "./prometheus.yml/:/etc/prometheus/prometheus.yml"

  grafana:
    expose:
      - "3000"
    ports:
      - "0.0.0.0:3000:3000"
    networks:
      - backend
    image: grafana/grafana:latest
networks:
  backend:
