global:
  external_labels:
    role: "remote"
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'

    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'coordinator'
    static_configs:
      - targets: ['m3coordinator01:7203']

  - job_name: 'dbnode'
    static_configs:
      - targets: ['m3db_seed:7203']

remote_read:
  - url: http://m3coordinator01:7201/api/v1/prom/remote/read

remote_write:
  - url: http://m3coordinator01:7201/api/v1/prom/remote/write
